#!bin/sh

## autoload vcs and colors
autoload -Uz add-zsh-hook vcs_info
autoload -U colors && colors

# enable only git
zstyle ':vcs_info:' enable git

# setup a hook that runs before every ptompt.
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

# from https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples
zstyle ':vcs_info:git+set-message:*' hooks git-changes git-st
zstyle ':vcs_info:*' formats ' %F{red}(%b)%f%c'

+vi-git-changes(){
  if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] ; then
    if git status --porcelain | grep '??' &> /dev/null ; then
      count=$(git status --porcelain | grep -c '??')
      hook_com[staged]+=' %F{green}'$count'%f'
    fi
    if git status --porcelain | grep 'M' &> /dev/null ; then
      count=$(git status --porcelain | grep -c 'M')
      hook_com[staged]+=' %F{yellow}'$count'%f'
    fi
    if git status --porcelain | grep 'D' &> /dev/null ; then
      count=$(git status --porcelain | grep -c 'D')
      hook_com[staged]+=' %F{red}'$count'%f'
    fi
    if git status --porcelain | grep 'A' &> /dev/null ; then
      count=$(git status --porcelain | grep -c 'A')
      hook_com[staged]+=' %F{magenta}'$count'%f'
    fi
    if git stash list | grep 'stash' &> /dev/null ; then
      count=$(git stash list | grep -c 'stash')
      hook_com[staged]+=' %F{white}'$count'%f'
    fi
  fi
}

function +vi-git-st() {
  local ahead behind
  local -a gitstatus

  # Exit early in case the worktree is on a detached HEAD
  git rev-parse ${hook_com[branch]}@{upstream} >/dev/null 2>&1 || return 0

  local -a ahead_and_behind=(
      $(git rev-list --left-right --count HEAD...${hook_com[branch]}@{upstream} 2>/dev/null)
  )

  ahead=${ahead_and_behind[1]}
  behind=${ahead_and_behind[2]}

  (( $ahead )) && gitstatus+=( "+${ahead}" )
  (( $behind )) && gitstatus+=( "-${behind}" )

  hook_com[misc]+=${(j:/:)gitstatus}
}

# 
PROMPT=' 強 %F{red}%n%f:'
PROMPT+='['
PROMPT+='%F{white}%1~%f'
PROMPT+='$vcs_info_msg_0_'
PROMPT+=']'
PROMPT+=' $ '
